version: "3.9"

services:
  backend:
    build: ./modelSite-backend
    container_name: modelsite-backend
    ports:
      - "8000:8000"
    volumes:
      - ./modelSite-backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "python app/database/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    build: ./modelSite-frontend
    container_name: modelsite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./modelSite-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
